### ISSUE TITLE
behavior conflicts with CGridView

### ISSUE THREAD

**Issue by RusAlex** [yiiext/trash-bin-behavior#3]
When i use that behavior and also use CGridView for model, it shows me an incorrect counts of total models in CGridView and therefore incorrect pagination.

**Comment by RusAlex** [comment]
im sorry. i just need a correct dataporvider form function

**Comment by timofei-iatsenko** [comment]
What did you exactly do with dataprovider? I can't uderstand what did you mean in previous post.

I have the same problem, and i really dont want to waste time to solve fixed issue again...

**Comment by cebe** [comment]
@thekip you can set dataProviders total Item Count manually. As beforeFind() event does not apply to count() method on active record the count result is not the number of items returned by find().
feature request for this to be fixed can be found here: yiisoft/yii#1353
