### ISSUE TITLE
Column is ambiguous

### ISSUE THREAD

**Issue by rrhyne** [yiiext/trash-bin-behavior#5]
When using this extension to access a model relation, I received the error:

"CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'is_deleted' in where clause is ambiguous."

The fix is to change line 118 of ETrashBinBehavior.php to add Yii's common table alias 't.'. to the field name condition:

$criteria->addCondition('t.'.$this->trashFlagField.'!='.CDbCriteria::PARAM_PREFIX.CDbCriteria::$paramCount);

**Comment by yesaulov** [comment]
i get the same error, and i think insert "t." is not best solution, and i fix with 

``` php
$criteria->addCondition($owner->tableAlias.".".$this->trashFlagField.'!='.CDbCriteria::PARAM_PREFIX.CDbCriteria::$paramCount);
```

by adding $owner->tableAlias.".".

**Comment by cebe** [comment]
Fixed. Thanks for suggestion and reporting!
