### ISSUE TITLE
Need to ensure beforeFind works with relation

### ISSUE THREAD

**Issue by cebe** [yiiext/trash-bin-behavior#6]
yiisoft/yii#1102

**Comment by slavcodev** [comment]
The extension does not work correctly for relations.

Because

``` php
TestPost::model()->withRemoved()->findAll();
// call TestPost::withRemoved > TestPost::beforeFind
```

``` php
TestUser::model()->with('posts:withRemoved')->findByPk(1)->posts;
// call TestPost::beforeFind > TestPost::withRemoved
```

**Comment by cbepxpa3ym** [comment]
I was glad when I found this extension. Implemented it in my app (did a lot of coding related to this new feature - to archive/unarchive records), but then I got this problem... this sucks :(

When it could be fixed?

**Comment by cbepxpa3ym** [comment]
Btw, this problem was discussed in 2009. I dont understand why next Yii releases dont have it fixed. Odd.

**Comment by cbepxpa3ym** [comment]
If to swap 2 lines in CActiveFinder, then this works.

change this:
$model->beforeFindInternal();
$model->applyScopes($criteria);

to this:
$model->applyScopes($criteria);
$model->beforeFindInternal();

Will it damage something? :)

**Comment by slavcodev** [comment]
Please pull your request in http://github.com/yiisoft/yii/issues

**Comment by cebe** [comment]
> Will it damage something? :)

Yep, does not allow to modify model criteria in `onBeforeFind` event anymore. This is not trivial to solve.

**Comment by acorncom** [comment]
@cebe I'm considering sending in a pull request that would merge aspects of https://github.com/fantgeass/deletable-behavior/blob/master/DeletableBehavior.php with this trashbin behavior.  Would that be something you'd like to see?  Or should I just handle things on my own and not try to send them back here?

**Comment by cebe** [comment]
@acorncom I don't know if I'd like to see it, I am not using or maintaining this extension :) better ask @slavcodev for this.
This task is just a reminder for me to check compatibility with a change I made in yii repo.

**Comment by acorncom** [comment]
@cebe :-)  Sounds good

**Comment by acorncom** [comment]
@slavcodev Seems like this extension could be really nifty if it handled relational soft deletes as well.  Thoughts?

**Comment by slavcodev** [comment]
Please create a new issue and describe what features u need.
