### ISSUE TITLE
withRemoved

### ISSUE THREAD

**Issue by rrhyne** [yiiext/trash-bin-behavior#7]
The withRemoved scope doesn't work when written as follows:  

$model = ModelName::model()->withRemoved->find($cond); 

No model is returned. 

This however, returns a deleted model:

$model = new ModelName;
$model $model->withRemoved->find($cond); 

Not sure if this is an issue, or a Yii thing, but it should probably be in the docs. 

Hope this helps. Thanks for a great Behavior!

**Comment by cebe** [comment]
Guess you have a syntax error
write `$model = ModelName::model()->withRemoved()->find($cond);` instead.
Note the brackets after withRemoved
